### PR TITLE
fix/broken movinglater imports

### PR DESCRIPTION
**Pull request by nllptr**
I couldn't install `buffalo-goth`, and this seemed to fix it.

### CODE REVIEW

**Comment by krotovic** [comment]
This is duplicate of #25

**Comment by denmat** [comment]
@krotovic I don't think it is a duplicate. I'm getting the errors described in https://github.com/gobuffalo/buffalo-goth/issues/24 and there is still references to movinglater in `master`.

```
± |master ✓| → grep movingl -rs *
cmd/generate.go:        "github.com/gobuffalo/genny/movinglater/gotools"
cmd/auth.go:    "github.com/gobuffalo/genny/movinglater/gotools"
genny/goth/goth_test.go:        "github.com/gobuffalo/genny/movinglater/gotools/gomods"
genny/goth/goth.go:     "github.com/gobuffalo/genny/movinglater/gotools"
genny/goth/goth.go:     "github.com/gobuffalo/genny/movinglater/gotools/gomods"
genny/auth/auth.go:     "github.com/gobuffalo/genny/movinglater/gotools"
shoulders.md:* [github.com/gobuffalo/genny/movinglater/gotools](https://godoc.org/github.com/gobuffalo/genny/movinglater/gotools)
shoulders.md:* [github.com/gobuffalo/genny/movinglater/gotools/goimports](https://godoc.org/github.com/gobuffalo/genny/movinglater/gotools/goimports)
shoulders.md:* [github.com/gobuffalo/genny/movinglater/gotools/gomods](https://godoc.org/github.com/gobuffalo/genny/movinglater/gotools/gomods)
```

**Comment by denmat** [comment]
Actually looks to be a duplicate of https://github.com/gobuffalo/buffalo-goth/pull/23

@markbates could either one of these be merged?

**Comment by markbates** [comment]
None of those PRs having passing tests. When there’s a PR that passes it’ll be merged. I’m focused on other issues, so someone else will need to write a passing PR.

**Pull request closed without merging**
